name: Gradle Build

on:
  push:
    branches:
      - main
      - releases/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: repo-read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3.3.0
    - name: Set up JDK
      uses: actions/setup-java@v3.11.0
      with:
        java-version: "20.0.1"
        distribution: 'temurin'
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1.0.5
    - name: Execute build
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: |
          jpackage
          --scan
          --refresh-dependencies
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
    - name: Upload EXE as an artifact
      if: ${{ matrix.os == 'windows-latest'}}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-windows-exe
        path: build/jpackage/*.exe
    - name: Upload MSI as an artifact
      if: ${{ matrix.os == 'windows-latest'}}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-windows-msi
        path: build/jpackage/*.msi
    - name: Upload DEB as an artifact
      if: ${{ matrix.os == 'ubuntu-latest'}}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-linux-deb
        path: build/jpackage/*.deb
    - name: Upload RPM as an artifact
      if: ${{ matrix.os == 'ubuntu-latest'}}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-linux-rpm
        path: build/jpackage/*.rpm
    - name: Upload DMG as an artifact
      if: ${{ matrix.os == 'macos-latest'}}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-macos-dmg-x86_64
        path: build/jpackage/*.dmg
    - name: Upload PKG as an artifact
      if: ${{ matrix.os == 'macos-latest'}}
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-macos-pkg-x86_64
        path: build/jpackage/*.pkg
