name: Gradle Build

on:
  push:
    branches:
      - main
      - releases/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: repo-read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3.3.0
    - name: Set up JDK
      uses: actions/setup-java@v3.9.0
      with:
        java-version: "19.0.1"
        distribution: 'adopt'
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1.0.5
    - name: Execute build
      uses: gradle/gradle-build-action@v2.3.3
      with:
        arguments: |
          jpackage
          --scan
          --refresh-dependencies
      env:
        USERNAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-${{ matrix.os }}-exe
        path: build/jpackage/*.exe
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-${{ matrix.os }}-msi
        path: build/jpackage/*.msi
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-${{ matrix.os }}-deb
        path: build/jpackage/*.deb
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cpm-filesystem-editor-${{ matrix.os }}-rpm
        path: build/jpackage/*.rpm
